### ISSUE TITLE
Follow consistent tagging name schema

### ISSUE THREAD

**Issue by stromvirvel** [michaeldale/mrpassword#7]
Hi :)

First of all: Many thanks for this nice tool, it's very helpful! 

I'm deploying automatic updates, including MrPassword (using ansible - I'll publish it in a few weeks on GitHub and Ansible Galaxy). I noticed that you have a non-consistent tagging schema. Your current releases/tags are:

- v.4.0.1
- 4.1

This is difficult for automation, because each time you break your schema, I have to update my ansible scripts :-(

Can I kindly ask you to follow the GitHub's tagging suggestions, which are:

> Tagging suggestions
> It’s common practice to prefix your version names with the letter v. Some good tag names might be v1.0 or v2.3.4.
> 
> If the tag isn’t meant for production use, add a pre-release version after the version name. Some good pre-release versions might be v0.2-alpha or v5.9-beta.3.

It would be nice if you could adjust your current tags/releases for it :)

Thank you very very much!

**Comment by michaeldale** [comment]
Why don't you use the built in update function?

But yes I will review tagging scheme and fix for future releases. Thanks.

**Comment by stromvirvel** [comment]
Many thanks!

We use ansible for deployment of our whole IT infrastructure. The code and code changes are documentation and audit at the same time, at a central source in our git repo. That's why we don't use built-in upgrading mechanisms.

**Comment by michaeldale** [comment]
Future releases will just be 4.1.1, 4.2 etc. No v. 

This matches the auto update system.

Thanks.

**Comment by stromvirvel** [comment]
Thanks a lot.
